name: Deploy Flutter Web a GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Instalar dependencias
        run: flutter pub get

      - name: Descargar motor de base de datos para Web
        run: dart run sqflite_common_ffi_web:setup

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/Y-Y_PRESTAMOS_IPHONE/"

      - name: Añadir .nojekyll
        run: touch build/web/.nojekyll

      - name: Añadir 404.html (para refrescos de rutas)
        run: cp build/web/index.html build/web/404.html

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
